/* Generated By:JavaCC: Do not edit this line. P1Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface P1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MINUS = 5;
  /** RegularExpression Id. */
  int ASSIGN = 6;
  /** RegularExpression Id. */
  int CLASS = 7;
  /** RegularExpression Id. */
  int METHOD = 8;
  /** RegularExpression Id. */
  int INTEGER = 9;
  /** RegularExpression Id. */
  int DECIMAL = 10;
  /** RegularExpression Id. */
  int DIGIT = 11;
  /** RegularExpression Id. */
  int LETTER = 12;
  /** RegularExpression Id. */
  int IDENTIFIER = 13;
  /** RegularExpression Id. */
  int INTEGER_NUMBER = 14;
  /** RegularExpression Id. */
  int DECIMAL_NUMBER = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"-\"",
    "\"=\"",
    "\"Clase\"",
    "\"metodo\"",
    "\"entero\"",
    "\"decimal\"",
    "<DIGIT>",
    "<LETTER>",
    "<IDENTIFIER>",
    "<INTEGER_NUMBER>",
    "<DECIMAL_NUMBER>",
    "\"{\"",
    "\"}\"",
    "\";\"",
  };

}
