/* Generated By:JavaCC: Do not edit this line. minilengcompilerConstants.java */
package analizador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface minilengcompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int tPROGRAMA = 11;
  /** RegularExpression Id. */
  int tVAR = 12;
  /** RegularExpression Id. */
  int tPRINCIPIO = 13;
  /** RegularExpression Id. */
  int tFIN = 14;
  /** RegularExpression Id. */
  int tSI = 15;
  /** RegularExpression Id. */
  int tENT = 16;
  /** RegularExpression Id. */
  int tSI_NO = 17;
  /** RegularExpression Id. */
  int tFSI = 18;
  /** RegularExpression Id. */
  int tMQ = 19;
  /** RegularExpression Id. */
  int tFMQ = 20;
  /** RegularExpression Id. */
  int tESCRIBIR = 21;
  /** RegularExpression Id. */
  int tLEER = 22;
  /** RegularExpression Id. */
  int tENTACAR = 23;
  /** RegularExpression Id. */
  int tCARAENT = 24;
  /** RegularExpression Id. */
  int tACCION = 25;
  /** RegularExpression Id. */
  int tVAL = 26;
  /** RegularExpression Id. */
  int tREF = 27;
  /** RegularExpression Id. */
  int tENTERO = 28;
  /** RegularExpression Id. */
  int tBOOLEANO = 29;
  /** RegularExpression Id. */
  int tCARACTER = 30;
  /** RegularExpression Id. */
  int tLLAVE_IZQ = 31;
  /** RegularExpression Id. */
  int tLLAVE_DER = 32;
  /** RegularExpression Id. */
  int tPARENTESIS_IZQ = 33;
  /** RegularExpression Id. */
  int tPARENTESIS_DER = 34;
  /** RegularExpression Id. */
  int tOPAS = 35;
  /** RegularExpression Id. */
  int tFIN_SENTENCIA = 36;
  /** RegularExpression Id. */
  int tSEP_VARIABLE = 37;
  /** RegularExpression Id. */
  int tMAS = 38;
  /** RegularExpression Id. */
  int tMENOS = 39;
  /** RegularExpression Id. */
  int tPRODUCTO = 40;
  /** RegularExpression Id. */
  int tDIVISION = 41;
  /** RegularExpression Id. */
  int tMOD = 42;
  /** RegularExpression Id. */
  int tDIV = 43;
  /** RegularExpression Id. */
  int tAND = 44;
  /** RegularExpression Id. */
  int tOR = 45;
  /** RegularExpression Id. */
  int tNOT = 46;
  /** RegularExpression Id. */
  int tMAYOR = 47;
  /** RegularExpression Id. */
  int tMENOR = 48;
  /** RegularExpression Id. */
  int tIGUAL = 49;
  /** RegularExpression Id. */
  int tMAI = 50;
  /** RegularExpression Id. */
  int tMEI = 51;
  /** RegularExpression Id. */
  int tNI = 52;
  /** RegularExpression Id. */
  int DIGITO = 53;
  /** RegularExpression Id. */
  int LETRA = 54;
  /** RegularExpression Id. */
  int tTRUE = 55;
  /** RegularExpression Id. */
  int tFALSE = 56;
  /** RegularExpression Id. */
  int tIDENTIFICADOR = 57;
  /** RegularExpression Id. */
  int tCONSTENTERA = 58;
  /** RegularExpression Id. */
  int tCONSTCHAR = 59;
  /** RegularExpression Id. */
  int tCONSTCAD = 60;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMENTARIO = 1;
  /** Lexical state. */
  int MULTICOMENTARIO = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\"%%\"",
    "\"\\n\"",
    "<token of kind 8>",
    "\"%%\"",
    "<token of kind 10>",
    "\"programa\"",
    "\"var\"",
    "\"principio\"",
    "\"fin\"",
    "\"si\"",
    "\"ent\"",
    "\"si_no\"",
    "\"fsi\"",
    "\"mq\"",
    "\"fmq\"",
    "\"escribir\"",
    "\"leer\"",
    "\"entacar\"",
    "\"caraent\"",
    "\"accion\"",
    "\"val\"",
    "\"ref\"",
    "\"entero\"",
    "\"booleano\"",
    "\"caracter\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\":=\"",
    "\";\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"mod\"",
    "\"div\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\">\"",
    "\"<\"",
    "\"=\"",
    "\">=\"",
    "\"<=\"",
    "\"<>\"",
    "<DIGITO>",
    "<LETRA>",
    "\"true\"",
    "\"false\"",
    "<tIDENTIFICADOR>",
    "<tCONSTENTERA>",
    "<tCONSTCHAR>",
    "<tCONSTCAD>",
  };

}
